name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  centos8:
    runs-on: ubuntu-latest

    container: centos:8

    steps:
      - run: |
          sed -i 's|#baseurl=|baseurl=|g'       /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|mirror|vault|g'             /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|http:|https:|g'             /etc/yum.repos.d/CentOS-*.repo

          dnf -y update
          dnf -y install curl xz gcc-c++

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm



      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/etc/ssl/certs/cacert.pem" >> $GITHUB_ENV


      - run:  ~/.ppkg/installed/uppm/bin/uppm

      - run:  ~/.ppkg/installed/uppm/bin/uppm --help
      - run:  ~/.ppkg/installed/uppm/bin/uppm --version

      - run:  ~/.ppkg/installed/uppm/bin/uppm -h
      - run:  ~/.ppkg/installed/uppm/bin/uppm -V

      - run:  ~/.ppkg/installed/uppm/bin/uppm env
      - run:  ~/.ppkg/installed/uppm/bin/uppm env -v

      - run:  ~/.ppkg/installed/uppm/bin/uppm integrate zsh

      - run:  ~/.ppkg/installed/uppm/bin/uppm update

      - run:  ~/.ppkg/installed/uppm/bin/uppm search zip

      - run:  ~/.ppkg/installed/uppm/bin/uppm depends zip
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk -t box
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk -t dot

      - run:  ~/.ppkg/installed/uppm/bin/uppm info @all
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip --json
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip --yaml
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip version
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip license
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip summary
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip webpage
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip bin-url
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip bin-sha
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip install
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip formula

      - run:  ~/.ppkg/installed/uppm/bin/uppm fetch   gzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm fetch   gsed -v

      - run:  ~/.ppkg/installed/uppm/bin/uppm install unzip

      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-dir
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-files
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-path
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-json
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-yaml
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-unix
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-iso-8601
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-rfc-3339
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-version

      - run:  ~/.ppkg/installed/uppm/bin/uppm tree unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm tree unzip -L 3

      - run: |
          sed -i '/^version: /c version: 6.0.28' $(~/.ppkg/installed/uppm/bin/uppm info unzip formula | head -n 1 | cut -d ' ' -f2)

      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-available
      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-installed
      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-outdated

      - run:  ~/.ppkg/installed/uppm/bin/uppm is-available curl
      - run:  ~/.ppkg/installed/uppm/bin/uppm is-installed unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm is-outdated  unzip

      - run:  ~/.ppkg/installed/uppm/bin/uppm upgrade   unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm reinstall unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm uninstall unzip


      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-list
      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-del my_repo

      - run:  ~/.ppkg/installed/uppm/bin/uppm cleanup

  centos7:
    runs-on: ubuntu-latest

    container: centos:7

    steps:
      - run:  yum -y update
      - run:  yum -y install curl xz gcc-c++

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm



      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/etc/ssl/certs/cacert.pem" >> $GITHUB_ENV


      - run:  ~/.ppkg/installed/uppm/bin/uppm

      - run:  ~/.ppkg/installed/uppm/bin/uppm --help
      - run:  ~/.ppkg/installed/uppm/bin/uppm --version

      - run:  ~/.ppkg/installed/uppm/bin/uppm -h
      - run:  ~/.ppkg/installed/uppm/bin/uppm -V

      - run:  ~/.ppkg/installed/uppm/bin/uppm env
      - run:  ~/.ppkg/installed/uppm/bin/uppm env -v

      - run:  ~/.ppkg/installed/uppm/bin/uppm integrate zsh

      - run:  ~/.ppkg/installed/uppm/bin/uppm update

      - run:  ~/.ppkg/installed/uppm/bin/uppm search zip

      - run:  ~/.ppkg/installed/uppm/bin/uppm depends zip
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk -t box
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk -t dot

      - run:  ~/.ppkg/installed/uppm/bin/uppm info @all
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip --json
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip --yaml
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip version
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip license
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip summary
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip webpage
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip bin-url
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip bin-sha
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip install
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip formula

      - run:  ~/.ppkg/installed/uppm/bin/uppm fetch   gzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm fetch   gsed -v

      - run:  ~/.ppkg/installed/uppm/bin/uppm install unzip

      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-dir
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-files
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-path
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-json
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-yaml
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-unix
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-iso-8601
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-rfc-3339
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-version

      - run:  ~/.ppkg/installed/uppm/bin/uppm tree unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm tree unzip -L 3

      - run: |
          sed -i '/^version: /c version: 6.0.28' $(~/.ppkg/installed/uppm/bin/uppm info unzip formula | head -n 1 | cut -d ' ' -f2)

      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-available
      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-installed
      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-outdated

      - run:  ~/.ppkg/installed/uppm/bin/uppm is-available curl
      - run:  ~/.ppkg/installed/uppm/bin/uppm is-installed unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm is-outdated  unzip

      - run:  ~/.ppkg/installed/uppm/bin/uppm upgrade   unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm reinstall unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm uninstall unzip


      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-list
      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-del my_repo

      - run:  ~/.ppkg/installed/uppm/bin/uppm cleanup

  centos_6_10:
    if: ${{ false }}

    runs-on: ubuntu-latest

    container: centos:6.10

    steps:
      - run: |
          sed -i 's|#baseurl=|baseurl=|g'       /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirror|vault|g'             /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|http:|https:|g'             /etc/yum.repos.d/CentOS-Base.repo

          yum -y update
          yum -y install curl xz gcc-c++

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm



      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/etc/ssl/certs/cacert.pem" >> $GITHUB_ENV


      - run:  ~/.ppkg/installed/uppm/bin/uppm

      - run:  ~/.ppkg/installed/uppm/bin/uppm --help
      - run:  ~/.ppkg/installed/uppm/bin/uppm --version

      - run:  ~/.ppkg/installed/uppm/bin/uppm -h
      - run:  ~/.ppkg/installed/uppm/bin/uppm -V

      - run:  ~/.ppkg/installed/uppm/bin/uppm env
      - run:  ~/.ppkg/installed/uppm/bin/uppm env -v

      - run:  ~/.ppkg/installed/uppm/bin/uppm integrate zsh

      - run:  ~/.ppkg/installed/uppm/bin/uppm update

      - run:  ~/.ppkg/installed/uppm/bin/uppm search zip

      - run:  ~/.ppkg/installed/uppm/bin/uppm depends zip
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk -t box
      - run:  ~/.ppkg/installed/uppm/bin/uppm depends android-sdk -t dot

      - run:  ~/.ppkg/installed/uppm/bin/uppm info @all
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip --json
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip --yaml
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip version
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip license
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip summary
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip webpage
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip bin-url
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip bin-sha
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip install
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip formula

      - run:  ~/.ppkg/installed/uppm/bin/uppm fetch   gzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm fetch   gsed -v

      - run:  ~/.ppkg/installed/uppm/bin/uppm install unzip

      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-dir
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-files
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-path
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-json
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-receipt-yaml
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-unix
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-iso-8601
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-timestamp-rfc-3339
      - run:  ~/.ppkg/installed/uppm/bin/uppm info unzip installed-version

      - run:  ~/.ppkg/installed/uppm/bin/uppm tree unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm tree unzip -L 3

      - run: |
          sed -i '/^version: /c version: 6.0.28' $(~/.ppkg/installed/uppm/bin/uppm info unzip formula | head -n 1 | cut -d ' ' -f2)

      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-available
      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-installed
      - run:  ~/.ppkg/installed/uppm/bin/uppm ls-outdated

      - run:  ~/.ppkg/installed/uppm/bin/uppm is-available curl
      - run:  ~/.ppkg/installed/uppm/bin/uppm is-installed unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm is-outdated  unzip

      - run:  ~/.ppkg/installed/uppm/bin/uppm upgrade   unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm reinstall unzip
      - run:  ~/.ppkg/installed/uppm/bin/uppm uninstall unzip


      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-list
      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-linux-x86_64
      - run:  ~/.ppkg/installed/uppm/bin/uppm formula-repo-del my_repo

      - run:  ~/.ppkg/installed/uppm/bin/uppm cleanup
